### ISSUE TITLE
how to know when the recaptcha is finish

### ISSUE THREAD

**Issue by fancy45daddy** [NopeCHALLC/nopecha-extension#50] opened 2024-06-06 03:00 UTC
I use playwright to solve recaptha, but how to know when the recaptcha is already finish?

**Comment by fancy45daddy** [comment] 2024-06-06 03:11
for example in https://www.google.com/recaptcha/api2/demo, how to how when I can click submit?

**Comment by Le0Developer** [comment] 2024-06-09 09:27
duplicate of #47

**Closed by Le0Developer** 2024-06-09 09:27 UTC
